use sha2::{Digest, Sha256};
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    println!("cargo:rerun-if-changed=assets/");

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let manifest_path = out_dir.join("asset_manifest.rs");

    // (logical_name, on-disk relative path, mime type)
    let assets = [
        ("app.css", "assets/app.css", "text/css; charset=utf-8"),
        (
            "client.js",
            "assets/client.js",
            "application/javascript; charset=utf-8",
        ),
        ("robots.txt", "assets/robots.txt", "text/plain; charset=utf-8"),
        ("favicon.ico", "assets/favicon.ico", "image/x-icon"),
        (
            "JetBrainsMono-Regular.woff2",
            "assets/fonts/JetBrainsMono-Regular.woff2",
            "font/woff2",
        ),
        (
            "JetBrainsMono-Bold.woff2",
            "assets/fonts/JetBrainsMono-Bold.woff2",
            "font/woff2",
        ),
        (
            "client_ws.js",
            "assets/client_ws.js",
            "application/javascript; charset=utf-8",
        ),
    ];

    let mut entries = String::new();
    entries.push_str(
        "// Auto-generated by build.rs (WS-D). Do not edit.\n\
         pub struct AssetEntry {\n\
         \x20   pub name: &'static str,\n\
         \x20   pub bytes: &'static [u8],\n\
         \x20   pub mime: &'static str,\n\
         \x20   pub hashed_name: &'static str,\n\
         \x20   pub hashed_path: &'static str,\n\
         }\n\n",
    );
    entries.push_str("pub const ASSETS: &[AssetEntry] = &[\n");

    for (name, path, mime) in assets.iter() {
        let bytes = match fs::read(path) {
            Ok(b) => b,
            Err(_) => continue, // optional asset, skip if absent
        };
        let hash = Sha256::digest(&bytes);
        // 8 hex chars = 4 bytes — plenty for cache busting.
        let hash_hex: String = hash.iter().take(4).map(|b| format!("{:02x}", b)).collect();
        let hashed_name = if let Some(dot) = name.rfind('.') {
            format!("{}.{}{}", &name[..dot], hash_hex, &name[dot..])
        } else {
            format!("{}.{}", name, hash_hex)
        };
        let hashed_path = format!("/p/_assets/{}", hashed_name);
        // Re-run when this specific file changes.
        println!("cargo:rerun-if-changed={}", path);
        entries.push_str(&format!(
            "    AssetEntry {{ name: \"{}\", bytes: include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/{}\")), mime: \"{}\", hashed_name: \"{}\", hashed_path: \"{}\" }},\n",
            name, path, mime, hashed_name, hashed_path
        ));
        let _ = bytes.len();
    }
    entries.push_str("];\n");

    fs::write(&manifest_path, entries).unwrap();

    // Preserve the existing tauri-build invocation.
    tauri_build::build()
}
